#!/usr/bin/env python3
#
prizes = [
   {'prize' : '$25 Starbucks Gift Card','taken':True},
   {'prize' : '$20 Starbucks Gift Card','taken':True},
   {'prize' : '$10 Starbucks Gift Card','taken':True},
   {'prize' : '$10 Starbucks Gift Card','taken':False},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$5 Starbucks Gift Card','taken':True},
   {'prize' : '$10 Subway Gift Card','taken':True},
   {'prize' : '$10 Subway Gift Card','taken':True},
   {'prize' : '$10 Subway Gift Card','taken':True},
   {'prize' : '$10 Target Gift Card','taken':True},
   {'prize' : '$10 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : "Tan Gift Basket",'taken':True},
   {'prize' : "Black Gift Basket",'taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
   {'prize' : '$5 Target Gift Card','taken':True},
]